spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orionerp}
    username: ${DB_USER:orion}
    password: ${DB_PASS:orion_secret_2024}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.orionerp: DEBUG
    org.springframework.security: DEBUG
