spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5

  jpa:
    show-sql: false

logging:
  level:
    com.orionerp: INFO
    org.springframework.security: WARN
