services:
  postgres:
    image: postgres:16-alpine
    container_name: orbitcrm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orbitcrm
      POSTGRES_USER: orbitcrm
      POSTGRES_PASSWORD: orbitcrm
    ports:
      - '5432:5432'
    volumes:
      - orbitcrm_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: orbitcrm-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    container_name: orbitcrm-minio
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - orbitcrm_minio:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: orbitcrm-mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    container_name: orbitcrm-api
    env_file:
      - .env.example
    environment:
      DATABASE_URL: postgresql://orbitcrm:orbitcrm@postgres:5432/orbitcrm?schema=public
      REDIS_URL: redis://redis:6379
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - postgres
      - redis
    ports:
      - '3001:3001'

  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    container_name: orbitcrm-web
    env_file:
      - .env.example
    environment:
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://api:3001
    depends_on:
      - api
    ports:
      - '3000:3000'

  nginx:
    image: nginx:1.27-alpine
    container_name: orbitcrm-nginx
    depends_on:
      - web
      - api
    ports:
      - '8080:80'
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  orbitcrm_postgres:
  orbitcrm_minio:
