server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sgcdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: minha-chave-super-segura-para-estudos-sgc-2026
  expiration: 86400000
